# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa08fc0267092cef8fe8ca026d7892378d5e2846e271f396f0f7c51eba975e89c6eb32f4f446550f81fd93a8fbadd75769144fb43e9bee2da699dae47710e52

test:
  secret_key_base: cfe82b86e78127f4304acc38dc2cacbe963feb58abdae7f2ec89f07682d56509013818c8523f5889ab4bb26ca3ae6a3304416ab9de08183fab183d6ee98446c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
